### ISSUE TITLE
20th year anniversary to highlight the history & celebrate open source project

### ISSUE THREAD

**Issue by leogopal** [leogopal/Community-Issue-Tracker#28]
Suggested by: [Naoko Takano](https://profiles.wordpress.org/nao/ "‌")

**Comment by leogopal** [comment]
> Junko Nukaga commented in Trello:

I'd like to get the 20th anniversary project going, maybe we can create a page similar to the one that was added to the handbook for the 15th anniversary.
https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/wordpress-15th-anniversary-celebrations/

**Comment by leogopal** [comment]
> naokomc commented in Trello:

@junko_nukaga My understanding is the "Anniversary Celebrations" page was created to serve as a page with more evergreen content.
https://make.wordpress.org/community/handbook/meetup-organizer/anniversary-celebrations/

**Comment by leogopal** [comment]
> naokomc commented in Trello:

I should have been more clear on this goal. I wanted to put weight on "highlight the history & celebrate open source project" part.

We could achieve this by, for example:

- Create a slide deck to include some information we want meetup organizers to share (history of the project, significance of community)
- Create a resource page for meetup organizers to create their own content for their events

**Comment by leogopal** [comment]
> Isotta Peira commented in Trello:

@naokomc ‌I love this idea, and I support it!  I’d give high priority to this task as the anniversary is just around the corner.

**Comment by naokomc** [comment]
Sorry about the late reply here – I created a slide deck for a Japanese community event.
https://speakerdeck.com/naokomc/wordpress-20-years-jp
